security_sudoers_passwordless:
  - radicle
security_autoupdate_enabled: true
security_autoupdate_reboot: false

firewall_state: started
firewall_enabled_at_boot: true

caddy_config: "{{ lookup('template', '../templates/Caddyfile.j2') }}"
# allow caddy to open ports under 1024 (e.g. 80 / 443)
caddy_setcap: true
caddy_systemd_capabilities_enabled: true
caddy_systemd_capabilities: "CAP_NET_BIND_SERVICE"